#+title: Reporti: TI-Inspired LaTeX Template.
#+latex_class_options: [english]
#+latex_class: reporti
#+options: toc:nil author:nil date:nil title:nil ::t prop:nil ^:t
#+language: en
#+PROPERTY: header-args :results silent :tangle ./reporti.cls 

#+LATEX:\subtitle{LaTeX Template}
#+LATEX:\author{Rhyloo - \href{mailto:jorge2@uma.es}{jorge2@uma.es}}
#+LATEX:\contact{\href{mailto :jorge2@uma.es}{Feedback about the documentation.}}
#+LATEX:\logo{rhyloo_solutions_horizontal.pdf}

#+LATEX:\type{README}
#+LATEX:\projectcode{REPORTI_DOC_TEMPLATE_v0.0}

#+LATEX:\summary{This document pretend to be the documentation of Reporti: A Texas-Instruments inspired LaTeX template.}

#+LATEX:\notes{Just copy it and modify under MIT.}

#+LATEX:\cover[width=1.35\textwidth][next]

#+begin_export markdown
> [!NOTE]
> This is a note.
#+end_export

* Motivation
At college I read lot of documents about electronics. One of my favorites was /[[https://e2echina.ti.com/cfs-file/__key/telligent-evolution-components-attachments/00-52-01-00-00-04-59-46/OP-amp-for-everyone.pdf][Op Amps for everyone]]/ from Texas Instruments (TI). If you take a moment to analyse the documents in the ~TI_Examples~ folder from this repository, you will agree with me that they are really well done, with great content and a nice design. So, after some time, I found free time to write a LaTeX template. To be honest with you, I don't use LaTeX where I work, and I am not sure if it's used anywhere else, but maybe I or future generations will have to write good nice reports or notes for some crazy school project. :D

So, here is the first version of Reporti, a Texas Instruments-inspired LaTeX template for you all.

#+ATTR_LATEX: :height 35em :options fbox
[[./README.pdf]]

#+begin_export latex
\begin{tcolorbox}[colback=yellow!5!white,colframe=red,title=Warning, fonttitle=\Large\bfseries,
  fontupper=\noindent,boxsep=2pt,enhanced,left=10pt,top=5pt, bottom=5pt,right=10pt]
  
I had the great idea of use the template for self documentation and I like to write in org-mode because my website run under it. So I can leverage this file for my website.

To sum‐up this README file has the full package inside thanks to org-babel, it works like jupyter notebooks but for any language (LaTeX, C, HTML and obviously python too).

So sorry if it is a mesh on github, I recommend you read README.pdf
\end{tcolorbox}
#+end_export

* How to use
If you are planning to use this template with LaTeX with linux download ~reporti.csl~ and put it in the path ....

#+begin_src bash :results drawer replace :exports both :tangle no 
find -L /home -samefile ./../Reporti/reporti.cls # 
#+end_src

#+RESULTS:
:results:
/home/rhyloo/Documents/LaTeX/Reporti/reporti.cls
/home/rhyloo/texmf/tex/latex/local/reporti.cls
/home/rhyloo/.emacs.d/reporti.cls
/home/rhyloo/snap/languagetool/45/Documents/LaTeX/Reporti/reporti.cls
/home/rhyloo/snap/languagetool/current/Documents/LaTeX/Reporti/reporti.cls
:end:

* Features
** Cover page
Just trying to keep it simple. A .cls file based on report class.

About features, the cover can be customize with the next commands: Check 

#+CAPTION: Control commands for the template
#+begin_src latex :tangle no :exports code
\documentclass[draft]{reporti}  %
\cover[width=1.35\textwidth][continue]
\type{Name of doc type}
\code{Project Number/Code} % For more info. Look for naming conventions
\titulo{Project title} 
\autor{Author}
\subtitulo{Subtitle}
\resumen{Summary}
\notes{Some notes in Cover}
\contact{Contact footnote}
#+end_src

** Table
#+Caption: Changelog
#+ATTR_LATEX: :placement [H]  
|---------+-----------------+--------|
| Version | Description     | Author |
|---------+-----------------+--------|
| v0.0    | Initial release | Rhyloo |
|---------+-----------------+--------|

** Images
#+ATTR_LATEX: :options fbox
#+Caption: Rhyloo Solutions's logo
[[./figures/logo/rhyloo_solutions_horizontal.pdf]]

* About images
The file ~Logo-EII-horizontal.pdf~ doesn't have any type of LICENSE on the [[https://www.uma.es/escuela-de-ingenierias-industriales/info/108566/logo-simbolo-de-la-eii/][web]]. As master's student I can use, maybe you don't, be careful with it.

I am really interested in naming conventions applied to projects. I think is the first part of a good story, I define two names the first is common use and the second is like a code, i.e Fat-Man is the bomb, but if I said Fat-Man-DOC-123HAJK123

Do you have one for owns?? Explain in comments and discuss the best :D

Examples:
- Texas Instruments have names like: TAS5518-5261K2EVM. According to Deepseek
  - TAS: Indicates a Texas Instruments Audio Solution
  - 5518: The specific model number of the IC.
  - 5261: A code unique to the EVM design
  - K2: Likely denotes a revision or variant of the EVM
  - EVM: Standard suffix for Evaluation Module

IMO is the first part of a good story like "MarkII" or "Apollo"


* About document class

#+begin_src latex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{reporti}[Template LaTeX based on Texas Instruments note application documentation.]
\LoadClass[10pt, a4paper, twoside]{article}
#+end_src

#+begin_src latex
\DeclareOption{draft}{
    \PassOptionsToPackage{draft}{graphicx}
    \AtEndOfClass{\usepackage{draftwatermark}\SetWatermarkText{DRAFT}}
}

\newcommand{\@mylang}{english}
% Language options
\DeclareOption{spanish}{\renewcommand{\@mylang}{spanish}}
\DeclareOption{english}{\renewcommand{\@mylang}{english}}

\DeclareOption*{\PassOptionsToClass{\CurrentOption}{article}}
\ProcessOptions\relax
#+end_src

** Packages
I added package geometry becuase I need to config headheight, and page geometry:
#+begin_src latex
\RequirePackage{geometry}      % Configuración de márgenes
\setlength{\headheight}{50pt} % 32.05278pt mínimo requerido + margen de seguridad
\geometry{top=3cm, bottom=2.5cm, left=1.83cm, right=1.83cm, footskip=1.2cm}
#+end_src

Encabezados/pies de página. I defined two styles.
1. mainstyle: Used for full document elaboration
2. tocstyle: Used by tocs.
#+begin_src latex
\RequirePackage{fancyhdr}      
\fancypagestyle{mainstyle}{
  \fancyhf{}
  \renewcommand{\headrulewidth}{2pt}
  \renewcommand{\footrulewidth}{1.5pt}
  \ifdefvoid{\@logo}{}{%
    \fancyhead[RE,LO]{\includegraphics[height=2em]{\@logo}\par
      \href{www.rhyloo.com}{www.rhyloo.com}\par\par}
    }
  \fancyhead[LE,RO]{\nouppercase{\rightmark}}
  \fancyfoot[LE]{{\fontsize{8}{35}\selectfont \thepage \hspace{0.8cm} \itshape\@title}}
  \ifdefvoid{\@contact}{\fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}}}}{%
    \fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}\\\itshape\@contact}}
    }
  \fancyfoot[RO]{{\fontsize{8}{35}\selectfont  \itshape\@title \hspace{0.8cm} \thepage}}
}

\fancypagestyle{tocstyle}{
  \fancyhf{}
  \renewcommand{\headrulewidth}{2pt}
  \renewcommand{\footrulewidth}{1.5pt}
  \ifdefvoid{\@logo}{}{%
    \fancyhead[RE,LO]{\includegraphics[height=2em]{\@logo}\par
      \href{www.rhyloo.com}{www.rhyloo.com}\par\par}
  }
  \fancyhead[LE,RO]{}
  \fancyfoot[LE]{{\fontsize{8}{35}\selectfont \thepage \hspace{0.8cm} \itshape\@title}}
  \ifdefvoid{\@contact}{\fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}}}}{%
    \fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}\\\itshape\@contact}}
  }
  \fancyfoot[RO]{{\fontsize{8}{35}\selectfont  \itshape\@title \hspace{0.8cm} \thepage}}
}

#+end_src

#+begin_src latex
\RequirePackage{xparse}        % Para comandos avanzados
#+end_src

#+begin_src latex

\RequirePackage{xcolor}        % Manejo de colores
\RequirePackage{titlesec}      % Estilos de secciones
\RequirePackage{graphicx}      % Manejo de imágenes

% Default: English

\RequirePackage[\@mylang]{babel}


\RequirePackage{hyperref}      % Hipervínculos
\hypersetup{
    colorlinks = true,
    linkcolor = blue!70!black,
    urlcolor = blue!70!black,
    citecolor = green!60!black
}


\RequirePackage{fontspec}      % Fuentes modernas
\setmainfont{FreeSans}


\RequirePackage[export]{adjustbox}
\RequirePackage{datetime2}     % Manejo de fechas profesional

\RequirePackage{etoolbox}      % Utilidades de macros
\RequirePackage{tabularx}
\RequirePackage{float}
\RequirePackage{booktabs}
\RequirePackage{multirow}
\RequirePackage{tocloft}
\RequirePackage[tableposition=above]{caption}
\RequirePackage[figure,table,listing]{totalcount}
\RequirePackage{xstring} % Add near the top of the file
\RequirePackage{underscore}
\RequirePackage{longtable}
\RequirePackage{wrapfig}
\RequirePackage{rotating}
\RequirePackage[normalem]{ulem}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{capt-of}


\RequirePackage[newfloat,outputdir=./build]{minted}
\usemintedstyle{emacs}
%% \newlistof{listing}{lol}{\hfill\bfseries\normalsize List of codes\hfill}
\RequirePackage{caption}

%% \newenvironment{code}{\captionsetup{type=listing}}{}
% Configure the listing environment

%% \captionsetup[listing]{
%%   name=Código, % Sets the caption name to "Código"
%%   %% listname=Lista de códigos % Name of the list of listings
%% }

\newcommand{\test}{Code}

\SetupFloatingEnvironment{listing}{%
  name={\test}}
\renewcommand{\thelisting}{\arabic{section}-\arabic{listing}}
%% \renewcommand{\cftlistingpresnum}{Code~}

%% \setlength{\cftlistingnumwidth}{5em}

% define a command that only prints the list if there is at least one listing
\newcommand{\maybeListOfListings}{%
  % \c@listing is the internal counter for float “listing”
  \ifnumcomp{\value{listing}}{>}{0}{%
    \listoflistings
  }{%
    No work!
  }%
}

\RequirePackage[most]{tcolorbox}
% Configuración de datetime2 para español
\DTMsetup{useregional=numeric}

\graphicspath{{figures/}{figures/logo/}}
#+end_src

** Doument Commands
#+begin_src latex
\newcommand{\@metadata}{} % Registro de metadatos

\NewDocumentCommand{\autor}{m}{%
    \def\@autor{#1}%
    \listadd{\@metadata}{Autor: #1}%
}
\NewDocumentCommand{\fecha}{O{\DTMtoday}}{%
    \def\@fecha{#1}%
    \listadd{\@metadata}{Fecha: #1}%
}
\NewDocumentCommand{\summary}{m}{%
    \def\@summary{#1}%
    \ifx\@summary\@empty\else
        \gappto\@afterabstract{\@printsummary}%
    \fi
}
\NewDocumentCommand{\subtitle}{m}{%
    \def\@subtitle{#1}%
    \listadd{\@metadata}{Subtítulo: #1}%  % Opcional: para mostrar en metadata
}
\NewDocumentCommand{\type}{m}{%
    \def\@type{#1}%
    \listadd{\@metadata}{Type: #1}%  % Opcional: para mostrar en metadata
}

\NewDocumentCommand{\projectcode}{m}{%
    \def\@projectcode{#1}%
    \listadd{\@metadata}{Projectcode: #1}%  % Opcional: para mostrar en metadata
}
\NewDocumentCommand{\notes}{m}{%
    \def\@notes{#1}%
    \listadd{\@metadata}{Notes: #1}%  % Opcional: para mostrar en metadata
}
\NewDocumentCommand{\contact}{m}{%
    \def\@contact{#1}%
    \listadd{\@metadata}{Contact: #1}%  % Opcional: para mostrar en metadata
}
\NewDocumentCommand{\toc}{m}{%
    \def\@toc{#1}%
    \listadd{\@metadata}{TOC: #1}%  % Opcional: para mostrar en metadata
}
\NewDocumentCommand{\logo}{m}{%
    \def\@logo{#1}%
    \listadd{\@metadata}{LOGO: #1}%  % Opcional: para mostrar en metadata
}


\renewcommand{\sectionmark}[1]{\markright{#1}}

% --- Redefinir marcas para ignorar subsecciones ---
\renewcommand{\sectionmark}[1]{\markright{#1}} % Actualiza solo \rightmark
\renewcommand{\subsectionmark}[1]{} % Subsecciones no modifican los headers


\pagestyle{mainstyle}


\fancypagestyle{titlepagestyle}{
  \renewcommand{\headrulewidth}{0pt}
  \renewcommand{\footrulewidth}{1.5pt}
  \fancyhf{}
  \fancyfoot[LE]{{\fontsize{8}{35}\selectfont \thepage \hspace{0.8cm} \itshape\@title}}
  \ifdefvoid{\@contact}{  \fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}}}}{
  \fancyfoot[RE,LO]{{\fontsize{8}{35}\selectfont \ifdefvoid{\@projectcode}{}{\@projectcode}\\\itshape\@contact}}}
  \fancyfoot[RO]{{\fontsize{8}{35}\selectfont  \itshape\@title \hspace{0.8cm} \normalfont\thepage}}
}

% ========================
% 4. Estilos de Títulos
% ========================
\setlength{\voffset}{10pt} % Ajusta según necesidad para evitar warnings
\setlength{\headsep}{5pt} % Ajusta según necesidad para evitar warnings

% Definir formato de títulos
\titleformat{\section}
  {\large\bfseries} % Formato del texto
  {\thesection.\hspace{2em}}   % Etiqueta: Número + 4em de espacio
  {0pt}                        % Separación entre etiqueta y título
  {}                           % Código antes del título

\titleformat{\subsection}
  {\large\itshape\bfseries}
  {\thesubsection.\hspace{1.25em}} % 3em de espacio
  {0pt}
  {}

\titleformat{\subsubsection}
  {\bfseries}
  {\hspace{3.5em}} % 2em de espacio
  {0pt}
  {}

% Ajustar espaciado vertical (opcional)
\titlespacing{\section}{0pt}{12pt}{6pt}
\titlespacing{\subsection}{0pt}{12pt}{6pt}
\titlespacing{\subsubsection}{0pt}{12pt}{6pt}



\newlength{\originalparskip}
% ========================
% 6. Cover
% ========================
\NewDocumentCommand{\cover}{O{width=0.8\textwidth} O{}}{%
  \pagestyle{empty}
  \begingroup % Grupo local para cambios de espaciado
  % Save the original parskip value
  \setlength{\originalparskip}{\parskip}
  \renewcommand{\baselinestretch}{0.4} % Ajuste principal (20% más de espacio)
  \renewcommand{\parskip}{\originalparskip} % Ajuste principal (20% más de espacio)
  \begin{titlepage}
  \thispagestyle{titlepagestyle} % <--- Aplica el footer
    % --------------------------
    % Cabecera con logo y datos institucionales
  % --------------------------
  \ifdefvoid{\@logo}
            {\vspace*{4em}}{}
  \noindent\begin{minipage}[t]{0.4\textwidth}
  \ifdefvoid{\@logo}
            {}
            {\includegraphics[#1]{\@logo}}
    %% \vspace{-1.5\baselineskip} % Alineación precisa
    \end{minipage}%
    \hfill
    \begin{minipage}[t]{0.6\textwidth}
      \vspace{-2\baselineskip} % Alineación precisa
      \raggedleft
      \ifdef{\@type}{\fontsize{14}{35}\selectfont\itshape\@type}{}\par
      \ifdef{\@projectcode}{\fontsize{9}{35}\selectfont\itshape\@projectcode}{}

    \end{minipage}
    
    \vspace{0.5\baselineskip} % Alineación precisa

    \begin{flushright}
      {\fontsize{18}{35}\selectfont\bfseries\itshape\@title}
    \end{flushright}
    \vspace*{-1\baselineskip} % Reduce espacio posterior
        {\rule{\textwidth}{2pt}}

        \noindent\begin{minipage}{0.7\textwidth}
        \raggedright
        \ifdef{\@author}{%
          {\fontsize{10}{35}\selectfont\itshape\@author}
        }{}
        \end{minipage}
        \hfill
        \begin{minipage}{0.25\textwidth}
        \raggedleft
        \ifdef{\@subtitle}{%
          {\fontsize{10}{35}\selectfont\itshape\@subtitle}
        }{}
        \end{minipage}

        % --------------------------
        % Summary condicional
        % --------------------------
        \ifdefvoid{\@summary}{}{%
          \vspace{0.75cm}

          \hspace{1.75cm}
          \begin{minipage}{13.6cm}
            \begin{center}
              \noindent{\bfseries ABSTRACT}
              \end{center}
            {\fontsize{10}{35}\selectfont\@summary}\par
            {\rule{\textwidth}{1pt}}
          \end{minipage}
        }
        \ifstrequal{#2}{continue}{
          \tocloftpagestyle{titlepagestyle}
          %% \vspace{0.75cm}

          \hspace{1.75cm}
          \begin{minipage}{13.6cm}
            {\fontsize{9}{35}\selectfont
              \tableofcontents
              \iftotalfigures
              \listoffigures
              \fi
              \iftotaltables
              \listoftables
              \fi
              \iftotallistings
              \listoflistings
              %% \maybeListOfListings
              \fi
            }
          \end{minipage}
        \vfill
        \ifdefvoid{\@notes}{}{%
          \noindent\raggedright{\fontsize{8}{35}\selectfont\@notes\vspace{-1\baselineskip}}}
  \end{titlepage}
  \endgroup}{
          \vfill
          \ifdefvoid{\@notes}{}{%
          \noindent\raggedright{\fontsize{8}{35}\selectfont\@notes\vspace{-1\baselineskip}}}
  \end{titlepage}
  \endgroup
  \tocloftpagestyle{tocstyle}
  \pagestyle{tocstyle}
  \tableofcontents
  \iftotalfigures
  \listoffigures
  \fi
  \iftotaltables
  \listoftables
  \fi
  \iftotallistings
  \listoflistings
  %% \maybeListOfListings
  \fi
  }
  \clearpage
  \pagestyle{mainstyle}
}

\AddToHook{cmd/section/before}{%
  \clearpage
}


\setlength{\cftbeforesecskip}{0pt}
\renewcommand{\cftsecleader}{\cftdotfill{\cftdotsep}}
\renewcommand{\cftdotsep}{1}% Default is 4.5

\renewcommand{\cftaftertoctitleskip}{2em}
\renewcommand{\cftafterloftitleskip}{2em}
\renewcommand{\cftafterlottitleskip}{2em}

\renewcommand{\cftfigindent}{0pt}
\renewcommand{\cftfigpresnum}{\figurename~}
\renewcommand{\cftfigaftersnum}{.}
\setlength{\cftfignumwidth}{5em}
\renewcommand{\thefigure}{\arabic{section}-\arabic{figure}}
\renewcommand{\cftsecpagefont}{\normalsize}


% =============================================
% List of Tables Customization
% =============================================
% 1. Set table numbering format: section-table (e.g., 1-1)
\renewcommand{\thetable}{\arabic{section}-\arabic{table}}

% 2. Configure table entries in List of Tables
\renewcommand{\cfttabindent}{0pt}               % Remove indentation
\renewcommand{\cfttabpresnum}{\tablename~}      % Prefix: "Table "
\renewcommand{\cfttabaftersnum}{.}              % Suffix: "."
\setlength{\cfttabnumwidth}{5em}                % Width for table numbers

% 3. (Optional) Set section page numbers in TOC
\renewcommand{\cftsecpagefont}{\normalsize}     % Normal font for section page numbers




\setlength{\parindent}{0pt}
\setlength{\baselineskip}{50pt}
\renewcommand{\baselinestretch}{1.2} % Ajuste principal (20% más de espacio)


\makeatletter
\apptocmd{\@afterheading}{
  \vspace{-0.5\baselineskip}
  \setlength{\parskip}{12pt}
  }{}{}
\makeatother



\addto\captionsspanish{%
  \renewcommand{\contentsname}{\hfill\bfseries\normalsize Contenido\hfill}
  \renewcommand{\figurename}{Figura} % Override figure name globally
  \renewcommand{\tablename}{Tabla}
  \renewcommand{\test}{Código}
\renewcommand{\listfigurename}{\hfill\bfseries\normalsize Lista de figuras\hfill}
\renewcommand{\listtablename}{\hfill\bfseries\normalsize Lista de tablas\hfill}
\renewcommand{\listlistingname}{\hfill\bfseries\normalsize Lista de códigos\hfill}
}

\addto\captionsenglish{%
  \renewcommand{\contentsname}{\hfill\bfseries\normalsize Content\hfill}
  \renewcommand{\tablename}{Table}
  \renewcommand{\figurename}{Figure} % Override figure name globally
  \renewcommand{\test}{Code}
\renewcommand{\listfigurename}{\hfill\bfseries\normalsize List of figures\hfill}
\renewcommand{\listtablename}{\hfill\bfseries\normalsize List of tables\hfill}
\renewcommand{\listlistingname}{\hfill\bfseries\normalsize List of codes\hfill}
}

\makeatletter
\renewcommand{\l@listing}[2]{%
  \renewcommand{\figurename}{\test} % Override figure name globally
  \l@figure{#1}{#2}%
}
\makeatother

\tocloftpagestyle{tocstyle}
#+end_src
* Known - Bugs
** TODO If there more than X sections the template do crazy things.
** TODO Change langs is not easy as I want.
** TODO Adjust toc style not in header
** TODO Modificar la web del header
* COMMENT Local variables
Local Variables:
eval: (add-hook 'after-save-hook
(lambda ()
(run-with-idle-timer
0.1 nil  ; espera 0.1 segundos antes de ejecutar el tangle
(lambda ()
(org-babel-tangle))))
nil t)
End:

